name: Bot tests
on:
  issue_comment:
    types: [created]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bot actions
        uses: zymap/bot@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.BKBOT_TOKEN }}
        with:
          repo_owner: apache
          repo_name: hudi
          rerun_cmd: rerun failure checks
          comment: ${{ github.event.comment.body }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: demo
        run: echo 123